name: todoapp_sample_riverpod
description: todoapp_sample_riverpod

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.8
  firebase_analytics: ^9.1.0
  flutter_riverpod: ^1.0.3
  state_notifier: ^0.7.2+1
  freezed_annotation: ^0.15.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  google_sign_in: ^5.2.4
  flutter_signin_button: ^2.0.0
  twitter_login: ^4.0.1
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.15.0+1
  build_runner: ^2.1.4
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true